name: Build Android APK

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.10'

    - name: Set up JDK 17
      uses: actions/setup-java@v4.4.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install System Dependencies
      run: |
        sudo apt update
        # सुधार: यहाँ से 'pathspec' हटा दिया गया है ताकि apt error न आए
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake libgdbm-dev libgdbm-compat-dev libsqlite3-dev libffi-dev xclip libx11-dev libxft-dev libasound2-dev libpulse-dev build-essential ccache
        pip install --upgrade pip setuptools virtualenv
        # pathspec को सही जगह (pip) पर डाल दिया है
        pip install "cython<3.0.0" "buildozer==1.5.0" "sh" "pathspec"

    - name: Build with Buildozer
      run: |
        export ANDROID_NDK_ROOT=""
        export ANDROID_NDK_HOME=""
        
        mkdir -p ~/.android && touch ~/.android/repositories.cfg
        
        buildozer android clean
        buildozer --verbose android debug
      env:
        ACCEPT_ANDROID_SDK_LICENSES: "y"

    - name: Upload APK
      uses: actions/upload-artifact@v4.6.1
      with:
        name: GPS-Tracker-App
        path: bin/*.apk
