name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    # 2026 के नए नियमों के अनुसार Node.js 24 को फ़ोर्स करना ज़रूरी है
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake libgdbm-dev libgdbm-compat-dev libsqlite3-dev libffi-dev xclip libx16-dev libxft-dev libffi7
        pip install --upgrade pip
        # Kivy कंपाइलेशन फेल न हो, इसलिए setuptools और cython का यह वर्जन ज़रूरी है
        pip install "setuptools<66.0.0" "cython<3.0.0" buildozer

    - name: Build APK with Buildozer
      run: |
        # बिल्डोज़र को ऑटोमैटिकली कॉन्फ़िगर करके रन करना
        buildozer android debug
      env:
        ACCEPT_ANDROID_SDK_LICENSES: "y"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Android-APK
        path: bin/*.apk
